### ISSUE TITLE
employee.customTable method throws args undefined error

### ISSUE THREAD

**Issue by martinwoit** [tresni/node-bamboohr#3]
Method for getting custom table throws "args undefined" error because of comment block.

employee.customTable(tableName, [id, ][data, ]callback)

```
Employee.prototype.customTable = function () {
  //var args = Array.prototype.slice.call(arguments, 0)
  //args.unshift('contacts')
  return this.__table_handler.apply(this, args)
}
```

**Comment by tresni** [comment]
doh!  This is likely due to me trying to work through a couple issues back then and not having tests around this area of the code.  Can you confirm whether replacing the function with:

```
Employee.prototype.customTable = function () {
    return this.__table_handler.apply(this, arguments)
}
```

fixes the issue for you?

**Comment by martinwoit** [comment]
Thanks for the fix :-)
