### ISSUE TITLE
Ability to add and change timeoff requests

### ISSUE THREAD

**Issue by alFReD-NSH** [tresni/node-bamboohr#4]
Hi,

I like to add the ability to add and change timeoff requests. Would you be open to contributions?

As for the code, I could either just add a couple of methods that handles those, or make a proper timeoff request class which as the methods attached to it, like the employee class. What do you think?

Aside that I also need to add a way to get the timeoff types.

**Comment by tresni** [comment]
Please feel free to open a pull request!! I'm definitely open for them!

The company I work for was aquired and we use a different HR system so I haven't spent much time here in the last year or so.
